on: [ push, pull_request ]
name: Lint
jobs:
    quality-tools:
        name: Run PHP-CS-Fixer & PHPStan
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Install dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: PHP-CS-Fixer
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --diff --dry-run

            -   name: PHPStan Static Analysis
                uses: php-actions/phpstan@v3
                with:
                    configuration: .phpstan.neon
